# Generated by Django 5.0.4 on 2024-06-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='to_room',
            new_name='room',
        ),
    ]
